# This is a basic workflow to help you get started with Actions

name: Deploy_Main

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: testing hetzner server ssh connection
        uses: appleboy/ssh-action@master
        with: 
          host: 168.119.224.9
          username: eddie
          key: ${{secrets.SANITIZER_GITHUB_SECRET}}
          port: 22
          script: | 
            cd /var/www/sanitizer/
            git pull origin main
            git status
